FROM golang:1.23-alpine AS builder 

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
RUN go build -ldflags="-s -w" -o main ./cmd/api

FROM alpine:latest 

COPY --from=builder ["/build/main", "/"]
COPY --from=builder ["/build/publicKey.pem", "/"]

ENTRYPOINT [ "/main" ]